services:
  drawdb:
    image: node:20-alpine
    container_name: drawdb
    ports:
      - 5173:5173
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - default
  backend:
    image: rust:1.83.0-slim
    ports:
      - 6666:6666
    working_dir: /app
    volumes:
      - ./backend/target/debug/:/app
    command: sh -c "bash backend.d"
    networks:
      - default
networks:
  default:
    driver: bridge
