//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "area")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub color: Option<String>,
    #[sea_orm(column_type = "custom(\"NUMERIC\")", nullable)]
    pub height: Option<String>,
    pub name: Option<String>,
    #[sea_orm(column_type = "custom(\"NUMERIC\")", nullable)]
    pub width: Option<String>,
    #[sea_orm(column_type = "custom(\"NUMERIC\")", nullable)]
    pub x: Option<String>,
    #[sea_orm(column_type = "custom(\"NUMERIC\")", nullable)]
    pub y: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
