//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use crate::entity::{field,indice,prelude::*};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "indice_link")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub field_id: Option<String>,
    pub indice_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Field",
        from = "Column::FieldId",
        to = "field::Column::Id"
    )]
    Field,
    #[sea_orm(
        belongs_to = "Indice",
        from = "Column::IndiceId",
        to = "indice::Column::Id"
    )]
    Indice
}

impl Related<Field> for Entity {
    fn to() -> RelationDef {
        Relation::Field.def()
    }
}

impl Related<Indice> for Entity {
    fn to() -> RelationDef {
        Relation::Indice.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
