//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod area;
pub mod diagram;
pub mod diagram_link;
pub mod field;
pub mod indice;
pub mod indice_link;
pub mod note;
pub mod reference;
pub mod table;
pub mod table_link;
pub mod task;
pub mod vo;