//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::area::Entity as Area;
pub use super::diagram::Entity as Diagram;
pub use super::diagram_link::Entity as DiagramLink;
pub use super::field::Entity as Field;
pub use super::indice::Entity as Indice;
pub use super::indice_link::Entity as IndiceLink;
pub use super::note::Entity as Note;
pub use super::reference::Entity as Reference;
pub use super::table::Entity as Table;
pub use super::table_link::Entity as TableLink;
pub use super::task::Entity as Task;
