//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

use crate::entity::prelude::DiagramLink;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "reference")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub cardinality: Option<String>,
    // fix-remote-github-issues-7-18（issue #12，core-01b §4.1）：关系线颜色
    // （迁移 0009_reference_color；'' = 跟随源表色 / 主题色）
    pub color: String,
    // fix-open-issues-19-22（#21）：线条类型 / 线型（迁移 0010）
    pub line_type: String,
    pub stroke_style: String,
    #[sea_orm(column_name = "deleteConstraint")]
    pub delete_constraint: Option<String>,
    #[sea_orm(column_name = "endFieldId")]
    pub end_field_id: Option<String>,
    #[sea_orm(column_name = "endTableId")]
    pub end_table_id: Option<String>,
    pub name: Option<String>,
    #[sea_orm(column_name = "startFieldId")]
    pub start_field_id: Option<String>,
    #[sea_orm(column_name = "startTableId")]
    pub start_table_id: Option<String>,
    #[sea_orm(column_name = "updateConstraint")]
    pub update_constraint: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "DiagramLink")]
    DiagramLink,
}

impl Related<DiagramLink> for Entity {
    fn to() -> RelationDef {
        Relation::DiagramLink.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
