//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use crate::entity::prelude::*;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub complete: Option<bool>,
    pub order: Option<i32>,
    pub details: Option<String>,
    pub title: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "DiagramLink")]
    DiagramLink,
}

impl Related<DiagramLink> for Entity {
    fn to() -> RelationDef {
        Relation::DiagramLink.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
